package org.sysc4806.sysc4806_group20.model;

public enum ProgramRestrictions {
    SOFTWARE_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    AEROSPACE_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    SUSTAINABILITY_ENGINEERING,
    CIVIL_ENGINEERING,
    COMMUNICATION_ENGINEERING,
    COMPUTER_SYSTEMS_ENGINEERING,
    ENGINEERING_PHYSICS,
    MECHATRONICS_ENGINEERING,
    RENEWABLE_ENERGY_ENGINEERING,
}
