package org.sysc4806.sysc4806_group20.Model;

public enum ProgramRestrictions {
    SOFTWARE,
    ELECTRICAL,
    AEROSPACE,
    BIOMEDICAL,
    ENVIRONMENTAL,
    MECHANICAL,
    SUSTAINABILITY,
    CIVIL,
    COMMUNICATION,
    COMPUTER_SYSTEMS,
    ENGINEERING_PHYSICS,
    MECHATRONICS,
    RENEWABLE_ENERGY,
}
